#pragma once

#define IDI_APP_ICON 101
#define IDR_HTML_AI_CHAT_HISTORY 201
#define IDR_HTML_AI_CONFIG_DIALOG 202
#define IDR_HTML_AI_PREVIEW_DIALOG 203
#define IDR_HTML_LINKER_CONFIG_DIALOG 204
#define IDR_HTML_EC_SWITCH_CONFIG_DIALOG 205
#define IDR_HTML_FORCE_LINK_LIB_CONFIG_DIALOG 206
#define IDR_HTML_AI_CHAT_THEME_CONFIG_DIALOG 207
#define IDR_HTML_PROJECT_AGENTS_CONFIG_DIALOG 208
#define IDR_HTML_AI_CHAT_MCP_CONFIG_DIALOG 209
#define IDR_HTML_AI_SKILL_CONFIG_DIALOG 214
#define IDR_HTML_AI_OTHER_SETTINGS 215
#define IDR_HTML_IDE_LOG_VIEWER 210
#define IDR_HTML_LOG_OPTIMIZATION_SETTINGS 211
#define IDR_HTML_ABOUT_SETTINGS 212
#define IDR_PNG_APP_ICON 213
