#pragma once

#define IDI_APP_ICON 101
#define IDR_HTML_AI_CHAT_HISTORY 201
#define IDR_HTML_AI_CONFIG_DIALOG 202
#define IDR_HTML_AI_PREVIEW_DIALOG 203
#define IDR_HTML_LINKER_CONFIG_DIALOG 204
#define IDR_HTML_EC_SWITCH_CONFIG_DIALOG 205
#define IDR_HTML_FORCE_LINK_LIB_CONFIG_DIALOG 206
#define IDR_HTML_AI_CHAT_THEME_CONFIG_DIALOG 207
